# Role is for SSM and CW logs.
# May not have correct SNS permissions.
# Code snippets https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudwatchlogs.html#quickref-cloudwatchlogs-example1
# ADD LOG GROUP FOR NGINX LOGS
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for CloudWatch Logs.
Resources:
  LogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
              #            - ssm.amazonaws.com # For SSM implementation see aws-ssm
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: CWLogRole
      Policies:
      - PolicyName: LogRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: #can be less restrictive, but pretty much full control EC2
            - logs:*
            - s3:* # Can add specific bucket in Resource area
            - ec2:*
            - autoscaling:*
            - cloudwatch:*
            - cloudformation:*
            - elasticloadbalancing:*
            Resource: "*"
  LogRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: LogRole
      InstanceProfileName: CWLogIProfile
Outputs:
  IamInstanceProfile:
    Description: "CW Logs Instance Profile"
    Value:
      !Ref LogRoleInstanceProfile
    Export:
      Name: CWLogIProfile

